baseURL = "http://example.org/"
languageCode = "fr-CH"
title = "Laboratoire de Veille Technologique"
theme = "ananke"
DefaultContentLanguage = "fr"

[params]
    featured_image = "/images/ashwin-vaswani-JqZ7q_S3xOE-unsplash.jpg"
